# Generated by Django 3.2.16 on 2022-11-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('item', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
    ]
