# Generated by Django 3.2.16 on 2022-11-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
